version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tenny-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tenny_ledger
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tenny-network

  backend:
    build:
      context: ./rust-backend
      dockerfile: Dockerfile
      no_cache: true
      args:
        - REBUILD=$(date +%s)
    container_name: tenny-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/tenny_ledger
      - RUST_LOG=info
      - JWT_SECRET=docker_jwt_secret_change_in_production
      - PORT=8080
      - HOST=0.0.0.0
    volumes:
      - ./uploads:/app/uploads
    networks:
      - tenny-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tenny-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api/proxy
      - RUST_API_URL=http://backend:8080
    networks:
      - tenny-network

networks:
  tenny-network:
    driver: bridge

volumes:
  postgres-data: 